# Generated by Django 4.0.4 on 2022-05-01 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_infomatsion_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infomatsion',
            name='photo',
            field=models.ImageField(default='photos/default.jpg', null=True, upload_to='photos/%Y/%m/%d/'),
        ),
    ]
