# Generated by Django 4.0.4 on 2022-05-01 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_infomatsion_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='infomatsion',
            name='faoliyat',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='infomatsion',
            name='mehnat',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='infomatsion',
            name='mukofot',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='infomatsion',
            name='project',
            field=models.IntegerField(default=0),
        ),
    ]
